<a href="https://colab.research.google.com/github/21-LAKSHMI/AI-AND-ML/blob/main/Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [2]:
dataset = pd.read_csv('/content/kidney_disease.csv')

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              400 non-null    int64
 1   age             391 non-null    float64
 2   bp              388 non-null    float64
 3   sg              353 non-null    float64
 4   al              354 non-null    float64
 5   su              351 non-null    float64
 6   rbc             248 non-null    object
 7   pc              335 non-null    object
 8   pcc             396 non-null    object
 9   ba              396 non-null    object
 10  bgr             356 non-null    float64
 11  bu              381 non-null    float64
 12  sc              383 non-null    float64
 13  sod             313 non-null    float64
 14  pot             312 non-null    float64
 15  hemo            348 non-null    float64
 16  pcv             330 non-null    object
 17  wc              295 non-null    object
 18  rc              270 non-null    object
 19  htn             398 non-null    object
 20  dm              398 non-null    object
 21  cad             398 non-null    object
 22  appet           399 non-null    object
 23  pe              399 non-null    object
 24  ane             399 non-null    object
 25  classification  400 non-null    object
dtypes: float64(11), int64(1), object(14)
memory usage: 81.4+ KB

In [4]:
dataset.head()

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,121.0,36.0,1.2,NaN,NaN,15.4,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,NaN,18.0,0.8,NaN,NaN,11.3,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,423.0,53.0,1.8,NaN,NaN,9.6,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,117.0,56.0,3.8,111.0,2.5,11.2,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,106.0,26.0,1.4,NaN,NaN,11.6,35,7300,4.6,no,no,no,good,no,no,ckd

In [5]:
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["al"]])

# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

data_imputed = scaler.inverse_transform(data_imputed)

# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["al"])

In [6]:
import numpy as np

In [7]:
# Round & clip 'al'
dataset[["al"]] = np.clip(np.round(imputed_df), 0, 5).astype(int)

In [8]:
dataset[["al"]].isnull().sum()

al    0
dtype: int64

In [9]:
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["bp"]])

# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

data_imputed = scaler.inverse_transform(data_imputed)

# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["bp"])

dataset[["bp"]] = imputed_df

In [10]:
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["sg"]])

# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

data_imputed = scaler.inverse_transform(data_imputed)

# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["sg"])

dataset[["sg"]] = imputed_df

In [11]:
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["su"]])

# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

data_imputed = scaler.inverse_transform(data_imputed)

# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["su"])

dataset[["su"]] = imputed_df

dataset[["su"]].isnull().sum()

su    0
dtype: int64

In [12]:
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["bgr"]])

# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

data_imputed = scaler.inverse_transform(data_imputed)

# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["bgr"])

dataset[["bgr"]] = imputed_df

dataset[["bgr"]].isnull().sum()

bgr    0
dtype: int64

In [13]:
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["bu"]])

# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

data_imputed = scaler.inverse_transform(data_imputed)

# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["bu"])

dataset[["bu"]] = imputed_df

dataset[["bu"]].isnull().sum()

bu    0
dtype: int64

In [14]:
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["sc"]])

# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

data_imputed = scaler.inverse_transform(data_imputed)

# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["sc"])

dataset[["sc"]] = imputed_df

dataset[["sc"]].isnull().sum()

sc    0
dtype: int64

In [15]:
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["sod"]])

# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

data_imputed = scaler.inverse_transform(data_imputed)

# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["sod"])

dataset[["sod"]] = imputed_df

dataset[["sod"]].isnull().sum()

sod    0
dtype: int64

In [16]:
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["pot"]])

# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

data_imputed = scaler.inverse_transform(data_imputed)

# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["pot"])

dataset[["pot"]] = imputed_df

dataset[["pot"]].isnull().sum()

pot    0
dtype: int64

In [17]:
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["hemo"]])

# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

data_imputed = scaler.inverse_transform(data_imputed)

# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["hemo"])

dataset[["hemo"]] = imputed_df

dataset[["hemo"]].isnull().sum()

hemo    0
dtype: int64

In [18]:
dataset["pcv"] = dataset["pcv"].replace({'\t?': np.nan})

In [19]:
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["pcv"]])

# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

data_imputed = scaler.inverse_transform(data_imputed)

# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["pcv"])

dataset[["pcv"]] = imputed_df

dataset[["pcv"]].isnull().sum()

pcv    0
dtype: int64

In [20]:
dataset["wc"] = dataset["wc"].replace({'\t?': np.nan})

In [21]:
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["wc"]])

# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

data_imputed = scaler.inverse_transform(data_imputed)

# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["wc"])

dataset[["wc"]] = imputed_df

dataset[["wc"]].isnull().sum()

wc    0
dtype: int64

In [22]:
dataset["rc"] = dataset["rc"].replace({'\t?': np.nan})

In [23]:
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["rc"]])

# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

data_imputed = scaler.inverse_transform(data_imputed)

# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["rc"])

dataset[["rc"]] = imputed_df

dataset[["rc"]].isnull().sum()

rc    0
dtype: int64

In [24]:
from sklearn.preprocessing import StandardScaler
# Scale features before imputation
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataset[["age"]])

# Step 2: Apply KNN Imputer
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
data_imputed = imputer.fit_transform(data_scaled)

data_imputed = scaler.inverse_transform(data_imputed)

# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed, columns=["age"])

dataset[["age"]] =np.round(imputed_df).astype(int)

dataset[["age"]].isnull().sum()

age    0
dtype: int64

In [25]:
display(dataset.head())

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48,80.0,1.020,1,0.0,NaN,normal,notpresent,notpresent,121.000000,36.0,1.2,137.528754,4.627244,15.4,44.0,7800.0,5.200000,yes,yes,no,good,no,no,ckd
1,1,7,50.0,1.020,4,0.0,NaN,normal,notpresent,notpresent,148.036517,18.0,0.8,137.528754,4.627244,11.3,38.0,6000.0,4.707435,no,no,no,good,no,no,ckd
2,2,62,80.0,1.010,2,3.0,normal,normal,notpresent,notpresent,423.000000,53.0,1.8,137.528754,4.627244,9.6,31.0,7500.0,4.707435,no,yes,no,poor,no,yes,ckd
3,3,48,70.0,1.005,4,0.0,normal,abnormal,present,notpresent,117.000000,56.0,3.8,111.000000,2.500000,11.2,32.0,6700.0,3.900000,yes,no,no,poor,yes,yes,ckd
4,4,51,80.0,1.010,2,0.0,normal,normal,notpresent,notpresent,106.000000,26.0,1.4,137.528754,4.627244,11.6,35.0,7300.0,4.600000,no,no,no,good,no,no,ckd

In [26]:
# Impute missing values in 'rbc' with the mode
rbc_mode = dataset['rbc'].mode()[0]
dataset['rbc'] = dataset['rbc'].fillna(rbc_mode)
display(dataset[['rbc']].isnull().sum())

rbc    0
dtype: int64

In [27]:
dataset = pd.get_dummies(dataset, columns=['rbc'], drop_first=True, dummy_na=False, dtype=int)
display(dataset.head())

,id,age,bp,sg,al,su,pc,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification,rbc_normal
0,0,48,80.0,1.020,1,0.0,normal,notpresent,notpresent,121.000000,36.0,1.2,137.528754,4.627244,15.4,44.0,7800.0,5.200000,yes,yes,no,good,no,no,ckd,1
1,1,7,50.0,1.020,4,0.0,normal,notpresent,notpresent,148.036517,18.0,0.8,137.528754,4.627244,11.3,38.0,6000.0,4.707435,no,no,no,good,no,no,ckd,1
2,2,62,80.0,1.010,2,3.0,normal,notpresent,notpresent,423.000000,53.0,1.8,137.528754,4.627244,9.6,31.0,7500.0,4.707435,no,yes,no,poor,no,yes,ckd,1
3,3,48,70.0,1.005,4,0.0,abnormal,present,notpresent,117.000000,56.0,3.8,111.000000,2.500000,11.2,32.0,6700.0,3.900000,yes,no,no,poor,yes,yes,ckd,1
4,4,51,80.0,1.010,2,0.0,normal,notpresent,notpresent,106.000000,26.0,1.4,137.528754,4.627244,11.6,35.0,7300.0,4.600000,no,no,no,good,no,no,ckd,1

In [28]:
# Impute missing values in 'rbc' with the mode
rbc_mode = dataset['pc'].mode()[0]
dataset['pc'] = dataset['pc'].fillna(rbc_mode)
display(dataset[['pc']].isnull().sum())

pc    0
dtype: int64

In [29]:
dataset = pd.get_dummies(dataset, columns=['pc'], drop_first=True, dummy_na=False, dtype=int)
display(dataset.head())

,id,age,bp,sg,al,su,pcc,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification,rbc_normal,pc_normal
0,0,48,80.0,1.020,1,0.0,notpresent,notpresent,121.000000,36.0,1.2,137.528754,4.627244,15.4,44.0,7800.0,5.200000,yes,yes,no,good,no,no,ckd,1,1
1,1,7,50.0,1.020,4,0.0,notpresent,notpresent,148.036517,18.0,0.8,137.528754,4.627244,11.3,38.0,6000.0,4.707435,no,no,no,good,no,no,ckd,1,1
2,2,62,80.0,1.010,2,3.0,notpresent,notpresent,423.000000,53.0,1.8,137.528754,4.627244,9.6,31.0,7500.0,4.707435,no,yes,no,poor,no,yes,ckd,1,1
3,3,48,70.0,1.005,4,0.0,present,notpresent,117.000000,56.0,3.8,111.000000,2.500000,11.2,32.0,6700.0,3.900000,yes,no,no,poor,yes,yes,ckd,1,0
4,4,51,80.0,1.010,2,0.0,notpresent,notpresent,106.000000,26.0,1.4,137.528754,4.627244,11.6,35.0,7300.0,4.600000,no,no,no,good,no,no,ckd,1,1

In [30]:
# Impute missing values in 'rbc' with the mode
rbc_mode = dataset['pcc'].mode()[0]
dataset['pcc'] = dataset['pcc'].fillna(rbc_mode)
display(dataset[['pcc']].isnull().sum())

pcc    0
dtype: int64

In [31]:
dataset = pd.get_dummies(dataset, columns=['pcc'], drop_first=True, dummy_na=False, dtype=int)
display(dataset.head())

,id,age,bp,sg,al,su,ba,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification,rbc_normal,pc_normal,pcc_present
0,0,48,80.0,1.020,1,0.0,notpresent,121.000000,36.0,1.2,137.528754,4.627244,15.4,44.0,7800.0,5.200000,yes,yes,no,good,no,no,ckd,1,1,0
1,1,7,50.0,1.020,4,0.0,notpresent,148.036517,18.0,0.8,137.528754,4.627244,11.3,38.0,6000.0,4.707435,no,no,no,good,no,no,ckd,1,1,0
2,2,62,80.0,1.010,2,3.0,notpresent,423.000000,53.0,1.8,137.528754,4.627244,9.6,31.0,7500.0,4.707435,no,yes,no,poor,no,yes,ckd,1,1,0
3,3,48,70.0,1.005,4,0.0,notpresent,117.000000,56.0,3.8,111.000000,2.500000,11.2,32.0,6700.0,3.900000,yes,no,no,poor,yes,yes,ckd,1,0,1
4,4,51,80.0,1.010,2,0.0,notpresent,106.000000,26.0,1.4,137.528754,4.627244,11.6,35.0,7300.0,4.600000,no,no,no,good,no,no,ckd,1,1,0

In [32]:
# Impute missing values in 'rbc' with the mode
rbc_mode = dataset['ba'].mode()[0]
dataset['ba'] = dataset['ba'].fillna(rbc_mode)
display(dataset[['ba']].isnull().sum())

ba    0
dtype: int64

In [33]:
dataset = pd.get_dummies(dataset, columns=['ba'], drop_first=True, dummy_na=False, dtype=int)
display(dataset.head())

,id,age,bp,sg,al,su,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification,rbc_normal,pc_normal,pcc_present,ba_present
0,0,48,80.0,1.020,1,0.0,121.000000,36.0,1.2,137.528754,4.627244,15.4,44.0,7800.0,5.200000,yes,yes,no,good,no,no,ckd,1,1,0,0
1,1,7,50.0,1.020,4,0.0,148.036517,18.0,0.8,137.528754,4.627244,11.3,38.0,6000.0,4.707435,no,no,no,good,no,no,ckd,1,1,0,0
2,2,62,80.0,1.010,2,3.0,423.000000,53.0,1.8,137.528754,4.627244,9.6,31.0,7500.0,4.707435,no,yes,no,poor,no,yes,ckd,1,1,0,0
3,3,48,70.0,1.005,4,0.0,117.000000,56.0,3.8,111.000000,2.500000,11.2,32.0,6700.0,3.900000,yes,no,no,poor,yes,yes,ckd,1,0,1,0
4,4,51,80.0,1.010,2,0.0,106.000000,26.0,1.4,137.528754,4.627244,11.6,35.0,7300.0,4.600000,no,no,no,good,no,no,ckd,1,1,0,0

In [34]:
# Impute missing values in 'rbc' with the mode
rbc_mode = dataset['htn'].mode()[0]
dataset['htn'] = dataset['htn'].fillna(rbc_mode)
display(dataset[['htn']].isnull().sum())

htn    0
dtype: int64

In [35]:
dataset = pd.get_dummies(dataset, columns=['htn'], drop_first=True, dummy_na=False, dtype=int)
display(dataset.head())

,id,age,bp,sg,al,su,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,dm,cad,appet,pe,ane,classification,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes
0,0,48,80.0,1.020,1,0.0,121.000000,36.0,1.2,137.528754,4.627244,15.4,44.0,7800.0,5.200000,yes,no,good,no,no,ckd,1,1,0,0,1
1,1,7,50.0,1.020,4,0.0,148.036517,18.0,0.8,137.528754,4.627244,11.3,38.0,6000.0,4.707435,no,no,good,no,no,ckd,1,1,0,0,0
2,2,62,80.0,1.010,2,3.0,423.000000,53.0,1.8,137.528754,4.627244,9.6,31.0,7500.0,4.707435,yes,no,poor,no,yes,ckd,1,1,0,0,0
3,3,48,70.0,1.005,4,0.0,117.000000,56.0,3.8,111.000000,2.500000,11.2,32.0,6700.0,3.900000,no,no,poor,yes,yes,ckd,1,0,1,0,1
4,4,51,80.0,1.010,2,0.0,106.000000,26.0,1.4,137.528754,4.627244,11.6,35.0,7300.0,4.600000,no,no,good,no,no,ckd,1,1,0,0,0

In [36]:
dataset['dm'] = dataset['dm'].replace({'\tno': 'no', '\tyes': 'yes', ' yes':'yes'})
display(dataset['dm'].value_counts())

dm
no     261
yes    137
Name: count, dtype: int64

In [37]:
# Impute missing values in 'rbc' with the mode
rbc_mode = dataset['dm'].mode()[0]
dataset['dm'] = dataset['dm'].fillna(rbc_mode)
display(dataset[['dm']].isnull().sum())

dataset = pd.get_dummies(dataset, columns=['dm'], drop_first=True, dummy_na=False, dtype=int)
display(dataset.head())

dm    0
dtype: int64

,id,age,bp,sg,al,su,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,cad,appet,pe,ane,classification,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes
0,0,48,80.0,1.020,1,0.0,121.000000,36.0,1.2,137.528754,4.627244,15.4,44.0,7800.0,5.200000,no,good,no,no,ckd,1,1,0,0,1,1
1,1,7,50.0,1.020,4,0.0,148.036517,18.0,0.8,137.528754,4.627244,11.3,38.0,6000.0,4.707435,no,good,no,no,ckd,1,1,0,0,0,0
2,2,62,80.0,1.010,2,3.0,423.000000,53.0,1.8,137.528754,4.627244,9.6,31.0,7500.0,4.707435,no,poor,no,yes,ckd,1,1,0,0,0,1
3,3,48,70.0,1.005,4,0.0,117.000000,56.0,3.8,111.000000,2.500000,11.2,32.0,6700.0,3.900000,no,poor,yes,yes,ckd,1,0,1,0,1,0
4,4,51,80.0,1.010,2,0.0,106.000000,26.0,1.4,137.528754,4.627244,11.6,35.0,7300.0,4.600000,no,good,no,no,ckd,1,1,0,0,0,0

In [38]:
# Impute missing values in 'rbc' with the mode
rbc_mode = dataset['cad'].mode()[0]
dataset['cad'] = dataset['cad'].fillna(rbc_mode)
display(dataset[['cad']].isnull().sum())

dataset = pd.get_dummies(dataset, columns=['cad'], drop_first=True, dummy_na=False, dtype=int)
display(dataset.head())

cad    0
dtype: int64

,id,age,bp,sg,al,su,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,appet,pe,ane,classification,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_no,cad_yes
0,0,48,80.0,1.020,1,0.0,121.000000,36.0,1.2,137.528754,4.627244,15.4,44.0,7800.0,5.200000,good,no,no,ckd,1,1,0,0,1,1,1,0
1,1,7,50.0,1.020,4,0.0,148.036517,18.0,0.8,137.528754,4.627244,11.3,38.0,6000.0,4.707435,good,no,no,ckd,1,1,0,0,0,0,1,0
2,2,62,80.0,1.010,2,3.0,423.000000,53.0,1.8,137.528754,4.627244,9.6,31.0,7500.0,4.707435,poor,no,yes,ckd,1,1,0,0,0,1,1,0
3,3,48,70.0,1.005,4,0.0,117.000000,56.0,3.8,111.000000,2.500000,11.2,32.0,6700.0,3.900000,poor,yes,yes,ckd,1,0,1,0,1,0,1,0
4,4,51,80.0,1.010,2,0.0,106.000000,26.0,1.4,137.528754,4.627244,11.6,35.0,7300.0,4.600000,good,no,no,ckd,1,1,0,0,0,0,1,0

In [39]:
# Impute missing values in 'rbc' with the mode
rbc_mode = dataset['appet'].mode()[0]
dataset['appet'] = dataset['appet'].fillna(rbc_mode)
display(dataset[['appet']].isnull().sum())

dataset = pd.get_dummies(dataset, columns=['appet'], drop_first=True, dummy_na=False, dtype=int)
display(dataset.head())

appet    0
dtype: int64

,id,age,bp,sg,al,su,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,pe,ane,classification,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_no,cad_yes,appet_poor
0,0,48,80.0,1.020,1,0.0,121.000000,36.0,1.2,137.528754,4.627244,15.4,44.0,7800.0,5.200000,no,no,ckd,1,1,0,0,1,1,1,0,0
1,1,7,50.0,1.020,4,0.0,148.036517,18.0,0.8,137.528754,4.627244,11.3,38.0,6000.0,4.707435,no,no,ckd,1,1,0,0,0,0,1,0,0
2,2,62,80.0,1.010,2,3.0,423.000000,53.0,1.8,137.528754,4.627244,9.6,31.0,7500.0,4.707435,no,yes,ckd,1,1,0,0,0,1,1,0,1
3,3,48,70.0,1.005,4,0.0,117.000000,56.0,3.8,111.000000,2.500000,11.2,32.0,6700.0,3.900000,yes,yes,ckd,1,0,1,0,1,0,1,0,1
4,4,51,80.0,1.010,2,0.0,106.000000,26.0,1.4,137.528754,4.627244,11.6,35.0,7300.0,4.600000,no,no,ckd,1,1,0,0,0,0,1,0,0

In [40]:
# Impute missing values in 'rbc' with the mode
rbc_mode = dataset['pe'].mode()[0]
dataset['pe'] = dataset['pe'].fillna(rbc_mode)
display(dataset[['pe']].isnull().sum())

dataset = pd.get_dummies(dataset, columns=['pe'], drop_first=True, dummy_na=False, dtype=int)
display(dataset.head())

pe    0
dtype: int64

,id,age,bp,sg,al,su,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,ane,classification,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_no,cad_yes,appet_poor,pe_yes
0,0,48,80.0,1.020,1,0.0,121.000000,36.0,1.2,137.528754,4.627244,15.4,44.0,7800.0,5.200000,no,ckd,1,1,0,0,1,1,1,0,0,0
1,1,7,50.0,1.020,4,0.0,148.036517,18.0,0.8,137.528754,4.627244,11.3,38.0,6000.0,4.707435,no,ckd,1,1,0,0,0,0,1,0,0,0
2,2,62,80.0,1.010,2,3.0,423.000000,53.0,1.8,137.528754,4.627244,9.6,31.0,7500.0,4.707435,yes,ckd,1,1,0,0,0,1,1,0,1,0
3,3,48,70.0,1.005,4,0.0,117.000000,56.0,3.8,111.000000,2.500000,11.2,32.0,6700.0,3.900000,yes,ckd,1,0,1,0,1,0,1,0,1,1
4,4,51,80.0,1.010,2,0.0,106.000000,26.0,1.4,137.528754,4.627244,11.6,35.0,7300.0,4.600000,no,ckd,1,1,0,0,0,0,1,0,0,0

In [41]:
# Impute missing values in 'rbc' with the mode
rbc_mode = dataset['ane'].mode()[0]
dataset['ane'] = dataset['ane'].fillna(rbc_mode)
display(dataset[['ane']].isnull().sum())

dataset = pd.get_dummies(dataset, columns=['ane'], drop_first=True, dummy_na=False, dtype=int)
display(dataset.head())

ane    0
dtype: int64

,id,age,bp,sg,al,su,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,classification,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_no,cad_yes,appet_poor,pe_yes,ane_yes
0,0,48,80.0,1.020,1,0.0,121.000000,36.0,1.2,137.528754,4.627244,15.4,44.0,7800.0,5.200000,ckd,1,1,0,0,1,1,1,0,0,0,0
1,1,7,50.0,1.020,4,0.0,148.036517,18.0,0.8,137.528754,4.627244,11.3,38.0,6000.0,4.707435,ckd,1,1,0,0,0,0,1,0,0,0,0
2,2,62,80.0,1.010,2,3.0,423.000000,53.0,1.8,137.528754,4.627244,9.6,31.0,7500.0,4.707435,ckd,1,1,0,0,0,1,1,0,1,0,1
3,3,48,70.0,1.005,4,0.0,117.000000,56.0,3.8,111.000000,2.500000,11.2,32.0,6700.0,3.900000,ckd,1,0,1,0,1,0,1,0,1,1,1
4,4,51,80.0,1.010,2,0.0,106.000000,26.0,1.4,137.528754,4.627244,11.6,35.0,7300.0,4.600000,ckd,1,1,0,0,0,0,1,0,0,0,0

In [42]:
from sklearn.model_selection import train_test_split
import time
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
import pickle
import matplotlib.pyplot as plt

In [43]:
dataset.columns

Index(['id', 'age', 'bp', 'sg', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot',
       'hemo', 'pcv', 'wc', 'rc', 'classification', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_no', 'cad_yes',
       'appet_poor', 'pe_yes', 'ane_yes'],
      dtype='object')

In [44]:
indep_X=dataset[['age', 'bp', 'sg', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot',
       'hemo', 'pcv', 'wc', 'rc','rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_no', 'cad_yes',
       'appet_poor', 'pe_yes', 'ane_yes']]

In [45]:
dep_Y=dataset[['classification']]

In [46]:
def split_scalar(indep_X,dep_Y):
        X_train, X_test, y_train, y_test = train_test_split(indep_X, dep_Y, test_size = 0.25, random_state = 0)

        sc = StandardScaler()
        X_train = sc.fit_transform(X_train)
        X_test = sc.transform(X_test)
        return X_train, X_test, y_train, y_test

In [50]:
def accuracy_prediction(classifier, X_test, y_test):
    y_pred = classifier.predict(X_test)
    from sklearn.metrics import accuracy_score
    accuracy = accuracy_score(y_test, y_pred)
    return accuracy

In [51]:
def Logistic(X_train, y_train, X_test, y_test):
    from sklearn.linear_model import LogisticRegression
    classifier = LogisticRegression(random_state = 0)
    classifier.fit(X_train, y_train)
    accuracy = accuracy_prediction(classifier, X_test, y_test)
    return accuracy

In [52]:
def Random_Forest_Classifier(X_train, y_train, X_test, y_test):
    from sklearn.ensemble import RandomForestClassifier
    classifier = RandomForestClassifier(n_estimators=100, random_state=0)
    classifier.fit(X_train, y_train)
    accuracy = accuracy_prediction(classifier, X_test, y_test)
    return accuracy

In [53]:
def DecisionTree(X_train, y_train, X_test, y_test):
    from sklearn.tree import DecisionTreeClassifier
    classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
    classifier.fit(X_train, y_train)
    accuracy = accuracy_prediction(classifier, X_test, y_test)
    return accuracy

In [68]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
indep_X_scaled = pd.DataFrame(
    scaler.fit_transform(indep_X),
    columns=indep_X.columns
)

In [72]:
def rfeFeature_classification(indep_X, dep_Y, n):
    rfelist = []
    colnames_list = []
    accuracy_values = []

    from sklearn.linear_model import LogisticRegression
    # Increased max_iter to address ConvergenceWarning
    log = LogisticRegression(random_state = 0, max_iter=5000)

    from sklearn.tree import DecisionTreeClassifier
    dec = DecisionTreeClassifier(random_state = 0)

    from sklearn.ensemble import RandomForestClassifier
    rf = RandomForestClassifier(n_estimators=10, random_state=0)

    # Added KNN back, but note that RFE with KNN might not work as expected
    # as KNN does not have coef_ or feature_importances_ attributes
    rfemodellist = [log, dec, rf]

    # Numerically encode the target variable before the loop
    from sklearn.preprocessing import LabelEncoder
    le = LabelEncoder()
    dep_Y_encoded = le.fit_transform(dep_Y.values.ravel())
    # Convert the encoded target variable back to a DataFrame with a column name
    dep_Y_encoded_df = pd.DataFrame(dep_Y_encoded, columns=['Species_Encoded'])


    for model in rfemodellist:
        # Ensure n_features_to_select is not greater than the number of features
        n_features = indep_X.shape[1]
        n_select = min(n, n_features)
        if n_select == 0:
            n_select = 1 # Ensure at least one feature is selected

        # Handle potential issue with RFE and models without feature importances/coefficients
        try:
            log_rfe = RFE(estimator=model, n_features_to_select=n_select)
            # Fit RFE with the original independent variables and the encoded dependent variable
            log_fit = log_rfe.fit(indep_X, dep_Y_encoded)
            log_rfe_feature = log_fit.transform(indep_X)
            selected_columns = [col for col, selected in zip(indep_X.columns, log_rfe.support_) if selected]
        except (AttributeError, ValueError) as e:
            print(f"Could not perform RFE with {type(model).__name__}: {e}")
            # If RFE fails, use all features
            log_rfe_feature = indep_X.values
            selected_columns = indep_X.columns.tolist()


        rfelist.append(log_rfe_feature)
        colnames_list.append(selected_columns)

        # Use split_scalar with the RFE selected features and the encoded dependent variable DataFrame
        # Ensure the selected features are in a DataFrame with correct column names for split_scalar
        X_train, X_test, y_train, y_test = split_scalar(pd.DataFrame(log_rfe_feature, columns=selected_columns), dep_Y_encoded_df)

        # Reshape y_train and y_test to 1D arrays for fitting and evaluation
        model.fit(X_train, y_train.values.ravel())
        accuracy = accuracy_prediction(model, X_test, y_test.values.ravel())
        accuracy_values.append(accuracy)

    return rfelist, colnames_list, accuracy_values

# Example usage (assuming you have classification data in indep_X and dep_Y)
rfelist, colnames_list, accuracy_values = rfeFeature_classification(indep_X, dep_Y, 5)

# Print the selected column names and accuracy values for each model
# Ensure model names list matches the rfemodellist
for model_name, selected_columns, accuracy_value in zip(["Logistic", "Decision", "Random"], colnames_list, accuracy_values):
     print(f"Model: {model_name}")
     print("Selected Columns:", selected_columns)
     print(f"Accuracy Value: {accuracy_value}\n")

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Model: Logistic
Selected Columns: ['al', 'rc', 'htn_yes', 'dm_yes', 'appet_poor']
Accuracy Value: 0.92

Model: Decision
Selected Columns: ['sg', 'bu', 'hemo', 'rc', 'htn_yes']
Accuracy Value: 0.99

Model: Random
Selected Columns: ['sg', 'bgr', 'sc', 'hemo', 'pcv']
Accuracy Value: 0.99

In [75]:
# Assuming you have classification data in indep_X_cls and dep_Y_cls
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep_X, dep_Y, test_size=0.30, random_state=0)

from sklearn.ensemble import RandomForestClassifier
classifier_dt = RandomForestClassifier(criterion='gini', random_state=0) # Common criteria are 'gini' or 'entropy'
classifier_dt.fit(X_train, y_train)

# # To evaluate the model using the accuracy_prediction function
accuracy_dt = accuracy_prediction(classifier_dt, X_test, y_test)
print(f"Decision Tree Classifier Accuracy: {accuracy_dt}")

/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

Decision Tree Classifier Accuracy: 0.9916666666666667

In [84]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

def classification_metrics(model, X_test, y_test):
    """
    Calculates and returns classification metrics for a given model.

    Args:
        model: Trained machine learning model.
        X_test: Test features.
        y_test: True labels for the test set.

    Returns:
        A dictionary containing accuracy, precision, recall, f1_score, and confusion_matrix.
    """
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')
    cm = confusion_matrix(y_test, y_pred)

    return {
        'accuracy': accuracy,
        'precision': precision,
        'recall': recall,
        'f1_score': f1,
        'confusion_matrix': cm
    }

In [86]:
# Calculate evaluation metrics for the Random Forest model
rf_metrics = classification_metrics(classifier_dt, X_test, y_test)

# Print the evaluation metrics
print("Random Forest Model Evaluation Metrics:")
print(f"Accuracy: {rf_metrics['accuracy']:.4f}")
print(f"Precision: {rf_metrics['precision']:.4f}")
print(f"Recall: {rf_metrics['recall']:.4f}")
print(f"F1-Score: {rf_metrics['f1_score']:.4f}")
print("\nConfusion Matrix:")
display(rf_metrics['confusion_matrix'])

Random Forest Model Evaluation Metrics:
Accuracy: 0.9917
Precision: 0.9834
Recall: 0.9917
F1-Score: 0.9875

Confusion Matrix:

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

array([[71,  0,  0],
       [ 1,  0,  0],
       [ 0,  0, 48]])